//TOURS reducer

export const GET_TOURS_BEGIN = "GET_TOURS_BEGIN"
export const GET_TOURS_SUCCESS = "GET_TOURS_SUCCESS"
export const GET_TOURS_ERROR = "GET_TOURS_ERROR"

export const GET_SINGLE_TOUR_BEGIN = "GET_SINGLE_TOUR_BEGIN"
export const GET_SINGLE_TOUR_SUCCESS = "GET_SINGLE_TOUR_SUCCESS"
export const GET_SINGLE_TOUR_ERROR = "GET_SINGLE_TOUR_ERROR"

export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS"
export const SIGNUP_USER_SUCCESS = "SIGNUP_USER_SUCCESS"
export const LOGOUT_USER_SUCCESS = "LOGOUT_USER_SUCCESS"
export const ERROR_USER = "ERROR_USER"

export const ME_UPDATE_SUCCESS = "ME_UPDATE_SUCCESS"
