//TOURS reducer

export const GET_TOURS_BEGIN = "GET_TOURS_BEGIN"
export const GET_TOURS_SUCCESS = "GET_TOURS_SUCCESS"
export const GET_TOURS_ERROR = "GET_TOURS_ERROR"

export const GET_SINGLE_TOUR_BEGIN = "GET_SINGLE_TOUR_BEGIN"
export const GET_SINGLE_TOUR_SUCCESS = "GET_SINGLE_TOUR_SUCCESS"
export const GET_SINGLE_TOUR_ERROR = "GET_SINGLE_TOUR_ERROR"

export const GET_SINGLE_TOUR_REVIEWS_BEGIN = "GET_SINGLE_TOUR_REVIEWS_BEGIN"
export const GET_SINGLE_TOUR_REVIEWS_SUCCESS = "GET_SINGLE_TOUR_REVIEWS_SUCCESS"
export const GET_SINGLE_TOUR_REVIEWS_ERROR = "GET_SINGLE_TOUR_REVIEWS_ERROR"
